name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: |
          build/_deps
          build/generated-includes
        key: ${{ runner.os }}-build-${{ secrets.CACHE_VERSION }}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DPERLBIND_BUILD_TESTS=ON -DCMAKE_CXX_STANDARD=14

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
